### PR TITLE
Bright

### PR DESCRIPTION
**Pull request by kps501**

### CODE REVIEW

**Comment by kps501** [comment]
@KMFDManic
Let's try this: remove small inline boost and move everything into mudlord.

**Comment by KMFDManic** [comment]
@kps501 

Ok, we will try it out!  On the "Bright" side, it works flawlessly on the PC Side of things!  Top Gear 3000 runs fantastic!  Just need to sort out the Nintendo Classics Portion!  Thanks again, and will follow-up with you!

**Comment by KMFDManic** [comment]
@kps501 Still works absolutely fine for PC.  It simply just wants to be stubborn for armhf, unfortunately!  Not sure exactly what the issue is, as the Standard 9x has no issues compiling.

**Comment by kps501** [comment]
Must be a strict armhf compiler. Same error messages or is it new one? Wondering if cx4dsp long long is also cracking.

**Comment by KMFDManic** [comment]
@kps501 Next step will be to try to debug it with log files.  I will keep you posted.  But, yes, same outcome.

**Pull request merged**
