### PR TITLE
improve direct bsx loading

### PR DESCRIPTION
**Pull request by kps501**
force lorom, hirom headers if no bios found

### CODE REVIEW

**Comment by kps501** [comment]
@KMFDManic 
Noticed that there's a decent amount of bsx games that don't need the bios, unlike the Sufami Turbo. So happy days all around.

**Comment by KMFDManic** [comment]
Cool @kps501, thanks, as always!  Really loving the "Bright" stuff.  Did you personally get to test out Top Gear 3000?

**Comment by kps501** [comment]
I played a few laps of Top Gear 3000 and didn't notice anything outside of inaccurate dsp4 emulation (mostly sprite popup timing).

**Comment by KMFDManic** [comment]
@kps501 I think I would like to introduce the Bright Variant of SNES9x to other NES/SNES Classic Enthusiasts.  I will do it in such a way, so as it can be enjoyed, as well as people still utilize SNES9x 2002, 2005, 2010, and 9x Standard:)  Rather than just keep adding things from Bright to 9x, let them enjoy the whole shebang, and I will keep you posted on feedback!  And, I will definitely be using it quite a bit, myself!  But, when I do my very next Update, I would love to post it, if you want others to enjoy the Experimental Awesomeness!

**Pull request merged**
