### PR TITLE
Bright4a

### PR DESCRIPTION
**Pull request by kps501**

### CODE REVIEW

**Comment by kps501** [comment]
@KMFDManic 
Let's try new approach, assuming that mudlord is still causing problems. Otherwise will need more error or sift through your compile logs - travis g++-7 is not throwing anything.

**Comment by KMFDManic** [comment]
@kps501 Bringing in a great friend @madmonkey to help assist on this one.  He is a great friend and has had a huge impact in the Mini Scene from day 1.  He, in fact, the first one to "hack" the Nes Classic 2 years ago.  And, he has also been detrimental to helping get some of the most stubborn Cores working, such as PPSSPP and DS!  It will be amazing to have "Bright" as part of the Mini Legacy in the near future, hopefully with the help of you two, as well as my other good friend gpstar (who is also helping in this endeavor!)

**Comment by KMFDManic** [comment]
@kps501 Bringing in a great friend @madmonkey1907 to help assist on this one.  He is a great friend and has had a huge impact in the Mini Scene from day 1.  He, in fact, the first one to "hack" the Nes Classic 2 years ago.  And, he has also been detrimental to helping get some of the most stubborn Cores working, such as PPSSPP and DS!  It will be amazing to have "Bright" as part of the Mini Legacy in the near future, hopefully with the help of you two, as well as my other good friend gpstar (who is also helping in this endeavor!)

**Comment by kps501** [comment]
@KMFDManic
Nice to hear you performing well as an overall emu manager. ;)

Having two more geniuses helping out  on this one is great! I'm stumped but at least we know it should be something simple, related to Bright itself. :)

I fully believe you that the reception when it works will be outstanding. No more dodgy HLE code - that alone is worth the entry price.

**Comment by KMFDManic** [comment]
@kps501 One thing I try to do is showcase anything that is committed:)  The smallest commits can have the biggest impact!  BSNES runs at a solid 7-11 FPS on the Minis!  Bright being able to handle many of the things that BSNES previously did, but at normal speed, is a fantastic addition all around.  I mix it up between doing Tech Videos and Silly Videos, of course.  And, feedback from End Users goes a long way as far as what I add in Updates.  If noone loved "sandbox", Grand Theft Auto would never have existed!  Bright is a place where literally any idea can be conceivably tried out without affecting the Main SNES9x.  And, based upon feedback, the "best of the coding" can make it into Mainline:)

**Comment by kps501** [comment]
When we get a working build up, what I'd be very curious about is how fast does latency runahead work on mini using Bright: internal runahead off vs on. Note that if internal is on, it will override frontend latency settings.

**Comment by kps501** [comment]
Awesome to hear the two got it pushed before the deadline. :mrgreen:

1a) Hardware dsp emulation (cx4,dsp1-4,st010-011) -- Hayazashi Nidan Morita Shougi (Japan), SD Gundam GX (Japan) are not playable yet in standard; Top Gear 3000 overall, F1 ROC II AI accuracy

1b) Memory randomization. This just means that the RNG seeder is changed on every clean game boot (not reset). If you watch the demo attract mode of standard (always Sidewinder) vs Bright (1st track can vary). This carries over when racing -- AI behavior, bonus items, etc.

1c) Hires blending - special mode. This activates a clean pseudo-transparency mode that works correctly with other Retroarch scaling shaders. Kirby's Dream Land 3 (USA / Japan), Jurassic Park (all regions), Bishoujo Senshi Sailor Moon S - Kondo wa Puzzle de Oshioki yo! (Japan). Standard blending is blurry.

1d) Blargg filter - monochrome. This is merely for fun.

1e) DSP-1 chipset. If set to 1/1a, Pilotwings plane demo will correctly land on the airstrip. Not with 1b (standard).

1f) Interlace speed. To see this in action, play Air Strike Patrol. Go to the radar briefing screen (new game). Standard will show text at 30fps. Bright can show the fast 60fps version. Or toggle to slow.

__________________________________________________________________
libretro port:
1g) Internal runahead. This is libretro feature, but libretro port is buggy when interlace is on (A.S.P. radar briefing). Bright fixes this bug and another libretro brief flicker bug when loading interlace savestates. Also libretro is buggy when playing lightgun games. Bright tries to fix this also.

1h) Overclocking. This is good for shooter games that suffer from slowdown. Gradius III in particular.

1i) Sprite Flicker. Shows more sprites at a time. Gradius III, Phalanx.

__________________________________________________________________

1j) Console Region + allow invalid vram access. This is more interesting when playing PAL games with copier protection removed. Play Marko's Magic Football (50 PAL) vs (60 NTSC) - much smoother. Same with Firemen (Europe), F1 World Championship Edition (Europe), World Masters Golf (Europe). This can also be done in standard through ini hacks, but less known. With vram access off, Marko+Golf+F1 is notably broken in NTSC mode.

That about covers everything other than interpolation.

**Comment by KMFDManic** [comment]
@kps501 That is more than enough to set up for a test video:)  As far as the memory randomization, any other games affected aside from Super Off Road?  What I will try to do for the test video is show a "before" and "After", so one can clearly see the changes in action and how they transition from "bad" to "much better".  Kirby and Jurassic Park had issues on the Default SNES Classic Emulator, Canoe, due to the same transparency issues.  This is a very nice thing indeed, amongst other additions you've mentioned!  I will try to get set-up and recorded within a day or so, and most likely get release by Weekend.  I will link you to the Release at the time, so you can see the feedback from End Users.  Thanks again.  I will update you with anything else, when it gets closer to Test Video time:)

**Comment by kps501** [comment]
I'm pretty sure there are other games that make use of randomization, but I honestly don't know which ones. No one else has notified me of any yet.

If there is a difference between dsp1/cx4 lle/hle, I haven't noticed yet.

**Comment by KMFDManic** [comment]
@kps501 I have been testing the Bright Core out, and so far, so good.  To confirm, your original info said to have BIOSES named as dsp1.bin, dsp2.bin, dsp3.bin, dsp4.bin, st0010.bin, and st0011.bin  Are the last two correct?  And, the latest one you did, should it be cx4.bin?  I have all the md5 hash checks, and just want to ensure the file names are correct.  And, a rough copy of the ReadMe, thus far, is...Keep in mind, due to a lot of confusion with many End Users, I have renamed SNES9x to SNES9x 2016, as well as FBA to FBA 2016, which has worked out quite well.  So, SNES9x 2016 is the Standard one, and SNES9x 2016 Bright is yours:)  In any case, here is the "rough draft" of the ReadMe.  Feel free to amend it anyway that you wish to!  I am gonna play around with the Core some more, and finalize the information file for it, as well, to account for the BIOSES!

```-----------------------
Name: km_SNES9x2016 Bright (7-4-18)
Creator: KMFDManic/madmonkey/kps501/gpstar
Category: KMFDManic Experimental Core Set
-----------------------
=== SNES9x2016 Bright Core for RetroArch ===

This particular SNES9x2016 Bright Variant offers some incredible, only seen before in
Higgan/BSNES, features!  These are all listed below!  It is a true sandbox experience
to test out potentially new and upcoming mainline additions to Standard SNES9x2016!  

Module adds support for Super Famicom / Super Nintendo

Available executables and arguments to run Core:
- /bin/snes <rom> <clover_args>
- /bin/snes-bright <rom> <clover_args>

Core by libretro

libretro commits by: kps501

Hakchi module system by madmonkey

NES/SNES Mini shell integration by Cluster

(c) 2016-2018

sandbox of snes9x (pre-1.56 rebase) for testing experimental features (meant for having fun only!!) -      ideally not recommended for upstream core inclusion (seriously, it's going to be messy clutter!)


dropoff 5:
- add byuu's nec dsp chipset code (dsp1-4,st010-011)
- add special chipset emulation: hardware, software
- fixed default gaussian volume
- fixed internal runahead soft reset


dropoff 4:
- improved direct bsx game loading (no bios)
- backport st010 accuracy fixes
- backport interlace fixes (Air Strike Patrol, F1 ROC II)
- clear interlace flicker on load state
- correctly apply settings on load state
- internal runahead interlace fixes (many)
- show interlace frames: even, odd, both


dropoff 3:
- internal runahead feature (good speedup)
- hires blending: disabled, half, full, special
- fix Lufia 2 interlace game id detection
- ignore bios option (bs-x, sufami turbo)
- try loading game even if bios missing
- backport Little Magic smp fix


dropoff 2:
- backport blargg ntsc filters: disabled, monochrome, rf, composite, s-video, rgb
- dsp-1 chipset: rev 1b, rev 1(a) (pilotwings light plane demo)
- interlace speed: auto (lufia 2 credits), slow, fast
- use special game hacks: enabled, disabled (emu testing)
- inline mudlord interpolation (small speedup)


dropoff 1:
- apply settings on boot and loadstate (sound channels, layers, misc)
- speakers mode: 16-bit stereo/mono, 8-bit stereo/mono, mute
- console region: auto, japan-usa (ntsc), europe (pal)
- allow invalid vram access: disabled, enabled (bad hacks, 60hz pal games, debugging)
- interpolation: 4-tap (4096 gaussian + no brr overflow), 8-tap (4096 sinc). default gaussian has brr overflow hardware error
- backport game fixes (Top Gear 3000, Dragon Ball Z: Super Butouden 2, Final Fantasy 6)
- change core name to Snes9x Bright

differences between Standard 9x and Bright:

- 1a) Hardware dsp emulation (cx4,dsp1-4,st010-011) -- Hayazashi Nidan Morita Shougi (Japan), SD Gundam GX (Japan) are not playable yet in standard; Top Gear 3000 overall, F1 ROC II AI accuracy

- 1b) Memory randomization. This just means that the RNG seeder is changed on every clean game boot (not reset). If you watch the demo attract mode of standard (always Sidewinder) vs Bright (1st track can vary). This carries over when racing -- AI behavior, bonus items, etc.

- 1c) Hires blending - special mode. This activates a clean pseudo-transparency mode that works correctly with other Retroarch scaling shaders. Kirby's Dream Land 3 (USA / Japan), Jurassic Park (all regions), Bishoujo Senshi Sailor Moon S - Kondo wa Puzzle de Oshioki yo! (Japan). Standard blending is blurry.

- 1d) Blargg filter - monochrome. This is merely for fun.

- 1e) DSP-1 chipset. If set to 1/1a, Pilotwings plane demo will correctly land on the airstrip. Not with 1b (standard).

- 1f) Interlace speed. To see this in action, play Air Strike Patrol. Go to the radar briefing screen (new game). Standard will show text at 30fps. Bright can show the fast 60fps version. Or toggle to slow.

libretro port:
- 1g) Internal runahead. This is libretro feature, but libretro port is buggy when interlace is on (A.S.P. radar briefing). Bright fixes this bug and another libretro brief flicker bug when loading interlace savestates. Also libretro is buggy when playing lightgun games. Bright tries to fix this also.

- 1h) Overclocking. This is good for shooter games that suffer from slowdown. Gradius III in particular.

- 1i) Sprite Flicker. Shows more sprites at a time. Gradius III, Phalanx.

additional notes:
- 4096 point interpolation will sound very similar to mudlord's 256 ones. Because Brad Miller is that good at using small tables to make high quality output. But for imaginary phantom audio benefits, 4/8-tap custom is the way to go!

- allow invalid vram access. This is useful for playing Europe in ntsc mode. Like Marko's Magic Football with copier protection disabled. Possibly Lucky Luke. World Masters Golf. And smoothing out some others. Or (old) translation hacks that don't work on real hardware. Plus newer hacks can abuse this feature and give lots of illegal speedup! And notably, this option breaks Hook gameplay.

- internal runahead feature. runs faster. Kirby's Dream Land 3 ## 0: 188 ## 1: 93 (frontend) ==> 104 (secondary) ==> 121 (internal). Also fixes lightgun cursor.

- hires blending special activates custom blending only for these games. extra compatible with lores scalers. Bishoujo Senshi Sailor Moon S - Kondo wa Puzzle de Oshioki yo, Kirby's Dream Land 3 / Hoshi no Kirby 3, Jurassic Park

- memory randomization. Only Super Off Road seems to use it so far.

- hardware chipset emulation. Name your files dsp1.bin, dsp1b.bin, dsp2.bin, dsp3.bin, dsp4.bin, st0010.bin, st0011.bin and place in Retroarch system folder.

- there's a rough chance of dropoff6 coming out. But there's honestly not much left to be added. Interest is naturally low. Likely almost no one will find out about this build and I can keep it a secret!

- if you actually enjoy using this win32 snes9x port, then erm. Thanks! And it's alright if you don't like/want/accept/use any of these features. They are leftovers and not intended for mainstream libretro community consumption.
```

**Comment by kps501** [comment]
You nailed everything! BIOS names were adopted from bsnes.

Forgot to mention that 4096 interpolation needs these files in Retroarch system folder:
https://github.com/kps501/bright_snes9x/tree/release/system

**Comment by KMFDManic** [comment]
@kps501 Thanks for the BIOS Updates.  I will adjust for those differentials.  Very nice work, all around.  To confirm one other small thing, Top Gear 3000 is still slightly imperfect with "minor graphical" popup, correct?  99.5 percent playable is still better than seizure inducing glitches, hehe:)  And, looking into the various special chips, dsp2 should also cover Dungeon Master, right?  Definitely many really cool things to check out, being a true sandbox:)  Will touch base with you again tomorrow!

**Comment by kps501** [comment]
@KMFDManic
To my knowledge, "sprite flicker on" might cause Top Gear 3000 to have a few odd sprite problems -- it does with Top Gear 1 when driving hills and tunnels. Otherwise it should be perfect using default options; any remaining popup would be original hardware problem and not emulator caused.

dsp2 = Dungeon Master family.

**Comment by KMFDManic** [comment]
@kps501 No need to watch the entire video!  But, I showcased a few of the things Bright can do:)

https://www.youtube.com/watch?v=lM1n1nSDr6c

Notables from testing!

- Mega Man X2/X3 have missing graphics in hardware mode.  But, they run fine in software

- Internal Runahead is useless on the Mini Classics due to the limited CPU/GPU.  But, it is an alternative slo-motion device:)

- Several games do not run well on Mini Classics on SNES9x, simply due to the same CPU/GPU limitations.  I typically recommend people use SNES9x2005 in these instances!  

Overall, very pleased with the Core, and it will be a mainstay!  I will post, likely this weekend, and you will get to see feedback for yourself!

Thanks again!  Enjoy the video and the fruits of your labor!!!

**Comment by kps501** [comment]
@KMFDManic
Watched entirety, which was pretty cool actually. You pulled out the important bits and it was fun to watch.

I kinda figured MMX2 CX4 LLE needs more work. I'll try checking it out myself. Thanks for all!

**Comment by KMFDManic** [comment]
@kps501 Glad you enjoyed the video.  It is a very solid Release in its current state.  If anything, people will be enjoying some games they never knew existed before:)  I will learn the Shogi/Shougi game, and play some of the SD Gundam!  And, I did enjoy F1- Rock II, as well:)  You shall see, Top Gear 3000 will make waves when I post the Core:)  It truly is one of the most incredible things to finally have going at 99.5 percent accuracy:)

**Comment by gingerbeardman** [comment]
This is astonishing work, very well done @kps501 - thanks, matt!

**Comment by kps501** [comment]
@KMFDManic
Could you point out which special effects to look for in MMX2/3?

I'll compare TG3K to bsnes+, no$sns - see  where this popup is coming from.

**Comment by KMFDManic** [comment]
@kps501 At least on the Mini Classics, if you have hardware enabled in Core Options, both Mega Man X2/X3 do not even display entire Mega Man character.  This may just be related to the Mini, if it functions fine on PC.  But, with software, graphics display absolutely fine.  Every other game ran fine with hardware enabled.  Again, very happy with the current status of the Core.

**Comment by kps501** [comment]
@KMFDManic 
Adjusted cx4 dsp some bit to give small speed and 64-bit ARM fixup? Also removed Kat's Run dma kludge (Phalanx fix).

**Comment by kps501** [comment]
@KMFDManic
DSP4 bios (1p full mode) is now hacked to allow max sprites, which needs another Bright update to allow max popup sprites (new option that will be separate from flicker, for unknown compatibility reasons). Will cut down speed for sure.

I think I'm not going to build dsp4 patch directly in emulator, as I might be starting a new project that will fix games with cpu overclocking problems.

Have to do more tg3k testing first.

**Comment by kps501** [comment]
@KMFDManic 
Raise sprite limit feature is working and installed on bright. It will auto-hack dsp4 bios to raise limits if option used. Game looks nicer now since you can sometimes see sprites further away. Some really heavy small particle games may benefit also.

**Comment by KMFDManic** [comment]
@kps501 Excellent.  I will continue to test new changes.  When I release it, it will be meant as a supplemental Core to go along with SNES9x Standard and SNES9x 2005.  It works out best to have all 3 installed, as you pretty much cover most games:)  I have been running nearly everything with Bright, lately.  Only the slower ones I have been running with 2005.  Madmonkey helped with one change that I am going to test, that may boost performance.  I still have a few more things to get together for the release, including another Custom OST (Real Songs, including Thriller) for MAME 2003 (Michael Jackson's Moonwalker).  Think MSU-1 with Arcade Games, essentially!  Gpstar is a great friend and asset in getting the Custom OSTs up and running.  He is currently trying to get flacs to work on the Mini for MAME 2003, which would be a pretty big thing, indeed.  Keep in touch:)

Test Video for Michael Jackson's Moonwalker, to show you what I am talking about:

https://www.youtube.com/watch?v=PhIBMtFJkI8

**Comment by KMFDManic** [comment]
@kps501 SNES9x Bright will go out this Saturday the 14th.  I will link you to the Release areas, so you can follow feedback on it.  Many are already looking forward, in anticipation, of its greatness:)  So, just a few more days, and it will be Live:)

**Comment by kps501** [comment]
@KMFDManic
Nice to know that someone (snes mini community) wants this core. Guess the PC world wants bsnes/higan 106. And upstream says no. But this doesn't distract me.

Toying around with the snes9x internal resampler (hermite). Wondering if it keeps the bass better than sinc -- some sounds are too clean, pristine, sanitized in that mode, and lacking in energy.

Otherwise just having fun messing around with other emus:
- Testing Sameboy with unlimited sprites; would like some type of overclock also sometime.

- Only some success porting mednafen-pce-accurate to libretro. Lots of compiler problems all-around.

- Same with Stella.

- Snes9x overclock compatibility patch project. Those speed improvement projects at rhdn forums are nice but they look like hell to do on real hardware (huge asm rewrites - Arcana, Super Ghouls n Ghosts, Lost Vikings II, Cacoma Knight). Even then, those projects still have slowdowns but hugely less. I prefer the easy approach (much less time consuming than doing it the right way).

- Porting ST018 arm3 to Bright. Worse with SGB.

I'll be around to read the release news.

**Comment by KMFDManic** [comment]
@kps501 @gingerbeardman 

Let the fun begin:)

https://www.reddit.com/r/miniSNESmods/comments/8z716m/new_snes9x_bright_core_michael_jacksons/

**Comment by kps501** [comment]
@kps501 @gingerbeardman
Dropoff 6 will be closed to make way for #7. This one could be performance dripper as I'm attempting some more things:

- more audio options like hermite + catmull-rom, floats (80% done). Adds?/retains? higher brightness. Some speech samples may sound clearer (Magical Popn)

- fast loading. When snes goes into quiet mode, run emu as fast as possible at non-overclocked for compatibility. Some normal boot times take 7+ seconds. (30%)

- try raising internal sample rate from 32040. (10% = no idea here whether will work, it's pretty locked at that rate).

And that is one enormous release. :O

**Comment by gingerbeardman** [comment]
> fast loading. When snes goes into quiet mode, run emu as fast as possible at non-overclocked for compatibility. Some normal boot times take 7+ seconds. (30%)

this is a really cool idea!

**Comment by KMFDManic** [comment]
@kps501 Very interesting developments.  Release went extremely well.  I am personally helping many adjust to the NEW Bright SNES9x Core:)  

One thing that is constantly asked of me, is whether light gun support could be implemented in some way, shape, or form.  Super Scope games.  Even if they worked with a mouse, or somehow were able to be controlled with a controller.  It would be a fun gimmick, to say the least.  I am currently able to run NES Light Gun Games/MAME Light Gun Games, just fine...using a mouse:)  That is more than sufficient for me.  I would love your take on this!

And, otherwise, keep up the awesomeness.  Only one possible thing could truly make things way cooler...SGB:)  But, we both know that is no easy task!

**Comment by kps501** [comment]
@KMFDManic
I was using a PC mouse to play lightgun games, and it was working around dropoff 3-4. Because frontend runahead had problems with it, I created internal runahead to fix input errors and tested that time too. So maybe around 5 or 6 it broke again.

I'll poke around and see what's wrong.

**Comment by kps501** [comment]
@KMFDManic @gingerbeardman
https://github.com/kps501/bright_snes9x/tree/release

Dropoff 7 Preview1 is ready. Notably lightguns (Super Scope, Justifier, MACS Rifle) using PC mouse work again. Fast loading which sometimes can severely cut down boring wait times (Pack-in-Video games). And cubic hermite spline (catmull-rom).

**Comment by KMFDManic** [comment]
@kps501 Gotta love Easter Eggs:)

```Interest is naturally low. Likely almost no one will find out about this build and I can keep it a secret!```

Will check things out.  Thank You!:)

**Comment by KMFDManic** [comment]
@kps501 Going to throw up a test demonstration today for light gun games.  I would like to showcase fast loading, as well.  Any specific games you feel will be noteworthy to display?  Also, given most lightguns function with CRT tvs, I would love to personally look into implementation of something such as aimtrak, which works on LCD, etc, too, since it utilizes a sensor.  Kind of curious how drivers would play out for the device on the various Cores:)

**Comment by kps501** [comment]
@KMFDManic
Nope. No ideas what else to highlight.

**Comment by kps501** [comment]
@KMFDManic @gingerbeardman
preview2 is ready. Adds lightgun cursor features and several hermite interpolators.

Note that mudlord's cubic acts like Catmull-Rom (~0.50 hermite) vs real cubic (1.0 hermite). For naming sake, cubic is still cubic. And 1.0 hermite is cubic spline.

Higher interpolation can mean smoother, extra blending, anti-aliasing, audio blur. And lower interpolation can give brighter, sharper, lower muddy but stronger rough edges.

Ignoring special chips and upstream bugs, Bright is nearly feature complete atm.

**Comment by gingerbeardman** [comment]
It would be great if we could find specific games to demonstrate the new features: sound, fast loading, chipsets, etc

**Comment by KMFDManic** [comment]
I just uploaded test video from yesterday's coding, running Super Scope 6 Games.

For next Core Set Release, I'd love to show more specific examples.

**Pull request merged**
