### PR TITLE
ignore bios option

### PR DESCRIPTION
**Pull request by kps501**
also included:
1) if bios not found, will try auto-loading rom like normal
2) remove bios header fix

also check here for more features you might want
https://github.com/kps501/bright_snes9x

### CODE REVIEW

**Comment by kps501** [comment]
I suggest compiling and testing before merging, just to be safe! Don't want to jinx the project like libretro/snes9x.

**Comment by KMFDManic** [comment]
@kps501 I highly doubt you will jinx this:)  I have absolute faith in this Commit:)  Thanks a hell of a lot for getting this to me, as many on the NES/SNES Classics will truly appreciate this Option!  bright_snes9x looks great, as well.  There is always a lot to do with SNES!  

You know what else might be interesting?  I know BSNES runs Super Game Boy.  mGBA can now Load the Palettes/Borders.  What are your thoughts on Super Game Boy, either real like with BSNES, or Pseudo, like with mGBA?  I am sure this is something you have thought about already!  But, I would absolutely love your opinion and thoughts on it!

Thanks again!

**Comment by kps501** [comment]
I think pseudo-sgb wouldn't work here since it still requires running a gameboy core with the snes. Full sgb would be a partial problem since we'd need to connect another gb core, and I'm not too sure how well they'd play together with the current upstream interface.

Still I think it's possible but with the right tools. Actually I thought about copy-paste-take bsnes+ dsp chip emulation (lle) to run st011 on snes9x but am running reverse engineering tests instead for dsp3,dsp4,st010 atm.

**Comment by kps501** [comment]
Some good news. snes9x bright dropoff 3 is now available. internal runahead feature pushes me from 93 to 121 on KDL3. Not sure if this would be enough for snes mini. But dp3 needs testing.

You can start a conversation here also to grab my attention about anything else that you'd like ported for your build.
https://github.com/kps501/bright_snes9x/issues

**Comment by kps501** [comment]
Thanks for checking things out! Bios ignore is actually useful sometimes outside of emu testing. I couldn't get bsx or st to work (bsnes or snes9x) and found it much easier to just direct load, using auto-detect method.

You can open an issue, ask for a backport or leave a reply in the bright fork. And I'll ship over whatever extra features you'd like. ;)
-- Although I consider bright mostly done, I've found some opcode issues with ST010 (op01, op04) and will send them upstream when my simulation work is done. Also looking at improving dsp4 accuracy also, since they're 0% bit-perfection checked. This will take awhile naturally but I'm committed to getting it through.

**Comment by KMFDManic** [comment]
Ok, to clarify things.  Pre-BS-X Direct Loading, "Some" Games still load.  These are ones that do not require patching to bypass the DRM, etc.  But, compatibility is pretty low, overall!  After BS-X Direct Loading, NONE of these Games will load, unless BIOS are present,  So, essentially, what it comes down to, is:

No BIOS=Low Compatibility (Only works on Pre-BS-X without Direct Loading Coding Change)

BIOS=High Compatibility (BIOS absolutely required!, or will not work!)

Patched=BIOS Ignored completely!  (Works, on Previous and Current Releases!)

Ignore BIOS, games failed to load, if BIOS were not present, unless they were specifically "Patched" Rom Sets.

This is not, at all, a big deal!  I am simply going to communicate with people in my next Release, exactly how things function, so there will be no confusion!  By implementing Direct BIOS Loading, you increased Compatibility Considerably!  This is a far better trade-off, than a handful of games previously working without Direct Loading!

I will gladly be testing other Bright Changes, too:)

Keep in touch!

**Comment by KMFDManic** [comment]
@kps501 Forgot to mention, I only get email notifications if you @ me:)  All others get ignored unless I "follow" a conversation.

**Pull request merged**
